### ISSUE TITLE
template.md implies should_print is special, but only mentions it in the examples. 

### ISSUE THREAD

**Issue by boynedmaster** [PyHP-pph/PyHP-pph#17]
https://github.com/PyHP-pph/PyHP-pph/blob/master/spec/template.md

In the default action tags, should_print is not listed anywhere, but is implied to be an action in the examples. should_print should be in the default action tags to be accurate.

**Comment by Boscillator** [comment]
`should_print` is not special. In that example `should_print` is aliased to `yes` using the `^` tag.

**Comment by boynedmaster** [comment]
Oh, I misunderstood. Closing.
